name: Build

on:
  push:
    branches: [ v1-rewrite ] # todo: set to master on v1 release
  pull_request:
    branches: [ v1-rewrite ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: yarn
    - run: yarn build