# modified from https://github.com/Impostor/Impostor/blob/master/.github/workflows/docker.yml

name: Docker

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    name: Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        id: prep
        run: |
          TAGS=hindenburg/hindenburg:${GITHUB_REF#refs/tags/},hindenburg/hindenburg:latest
          echo ::set-output name=tags::${TAGS}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/arm/v6,linux/ppc64le,linux/s390x
          push: true
          tags: ${{ steps.prep.outputs.tags }}
